FUNC LABEL 0
    MOV STK A VAL 6
    MOV REG 0 STK A
    CAL VAL 1
    MOV STK B VAL 7
    MOV REG 0 STK B
    CAL VAL 1
    PRINT REG 0
    PRINT REG 1
    RET
FUNC LABEL 1
    MOV REG 1 VAL 10
    ADD REG 0 REG 1
    EQU REG 0
    NOT REG 1
    RET
