FUNC LABEL 0
    MOV STK A VAL 7
    MOV STK B VAL 9
    REF REG 0 STK A
    REF REG 1 STK B
    CAL VAL 2
    ADD REG 0 REG 1
    PRINT REG 0
    RET
FUNC LABEL 2
    MOV STK A REG 0
    MOV STK B REG 1
    MOV REG 0 PTR A
    MOV REG 1 PTR B
    RET